### PR TITLE
feature: Add DSA5 (Das Schwarze Auge 5th Edition) system support

### PR DESCRIPTION
**Pull request by frankyh75**
# Add DSA5 System Support

This PR adds support for **Das Schwarze Auge 5th Edition (DSA5)** to Foundry MCP, enabling Claude to interact with DSA5 game worlds.

### Core Features
- ✅ DSA5 system detection and configuration
- ✅ 8-attribute system support (MU, KL, IN, CH, FF, GE, KO, KK)
- ✅ Compendium search for items, spells, liturgies, ceremonies
- ✅ Character data reading with DSA5-specific resources (LeP, AsP, KaP)
- ✅ Full item loading: weapons, armor, equipment, spells, blessings

### Bug Fixes
- 🐛 **Fixed:** Enhanced `stripHtml()` to handle all DSA5 item types
  - Resolved "text.replace is not a function" error
  - Now handles objects with `.value` property, arrays, and edge cases

### Documentation
- 📝 Installation guide: `INSTALL_DSA5.md`
- 📝 Development notes: `Claude.md`
- 📝 Comprehensive TODO document with roadmap

## 🧪 Testing

All core functionality tested and working:
- ✅ Character data reading
- ✅ Spells, liturgies, ceremonies, blessings
- ✅ Weapons and armor loading
- ✅ Compendium search (77 packs)
- ✅ No breaking changes to D&D 5e/Pathfinder 2e

### TODO for Future PRs
1. **Character Creation** (12-16 hours) - Template-based character creator
2. **Enhanced Creature Index** (8-12 hours) - DSA5 bestiary integration  
3. **Build Script Fix** (1 hour) - Fix composite project build command

See detailed analysis: [DSA5-PULL-REQUEST-TODO.md](link-to-file)

## 🔄 Compatibility

- ✅ Backward compatible with existing systems (D&D 5e, Pathfinder 2e)
- ✅ No breaking changes
- ✅ No new dependencies required
- ✅ Works with existing Foundry DSA5 system v7.2.0+

## 📊 Impact

- **Files Added:** 7 (DSA5 system files + docs)
- **Files Modified:** 3 (stripHtml fix, system detection)
- **Lines of Code:** ~800 added, ~50 modified

## 🙏 Credits

Built with assistance from Claude (Anthropic) - following the pattern established by the excellent D&D 5e and Pathfinder 2e implementations.

## 📚 Reference Documents

Detailed technical analyses available in PR branch:
- Character creation analysis (3 approaches, effort estimates)
- Build problem documentation  
- Comprehensive test reports
- Bug analysis and resolution

---

**Ready for review!** This provides a solid foundation for DSA5 support with clear roadmap for future enhancements.

### CODE REVIEW

**Comment by adambdooley** [comment]
Merged in v0.6.1 release. Thank you @frankyh75 for the excellent DSA5 implementation! Full SystemAdapter with all 8 Eigenschaften, creature indexing, and character creation is now live.

Release: https://github.com/adambdooley/foundry-vtt-mcp/releases/tag/v0.6.1

Closes #6
